### PR TITLE
feat/PTRC-3/data_and_env another try to add correctly new feat

### PR DESCRIPTION
**Pull request by konschat**
Please check if 'new feature' is added on feat/PTCR-3/data_and_env branch.

Questions :

1) In order to merge with main, both reviewers need to accept PR? 

2) Is this PR clearly related to the commit file(s) ?

### CODE REVIEW

**Review by georgiapant — CHANGES_REQUESTED** [review]
Testing request changes option of reviewal process. Please add feature :p

**Comment by konschat** [comment]
Waiting acceptance from all reviewers before merging. 

- would be helpful so please respond to PR questions
ALSO, how do you only accept a pull request, without merging it to main branch?

**Comment by georgiapant** [comment]
Ah sorry,  responding inline:

> Questions :
> 
> 1. In order to merge with main, both reviewers need to accept PR?

I don't think this is necessary in this case since we don't have this option enabled. Right now we can merge it even without any approvals. Probably in real life scenario this wont be possible. I don't know how the team works regarding this detail, we can ask.

> 2. Is this PR clearly related to the commit file(s) ?

Yes if you check on the top (see image) there are some tabs next to conversation which indicate what are the commits and what files have been changed and are requested to be merged in this pull request. 

image

> 3. ALSO, how do you only accept a pull request, without merging it to main branch?

The point of the PR is to finally merge it to the main branch. If you don't wish any merge then there is no point in creating a PR. That is at least my understanding. 

Maybe @michaelampalkoudi you can invite victor to the repo to verify our understanding of how these things work.

**Comment by konschat** [comment]
Thanks a lot Georgia, that was helpful!

I would suggest to keep Viktor out of this repo, I think it will mainly spam him. We can write our questions on teams.

**Review by georgiapant — APPROVED** [review]

**Pull request merged**
